# This is a basic workflow to help you get started with Actions

name: Deploy master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "first" branch
  push:
    branches: [ "first" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  curl-call:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: cURL request
        run: curl --location --request POST https://release-ee.appsmith.com/api/v1/git/deploy/app/65bdeb2e9e05cd61c71e31a7?branchName=master --header 'authorization: Bearer ${{ secrets.DEPLOY }}'
     
